name: CD - Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and update containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Go to project directory
            cd ~/product_browser

            # Pull latest code
            git pull origin main

            # Stop existing containers
            sudo docker compose down --remove-orphans

            # Clean unused Docker resources
            sudo docker builder prune -a -f
            sudo docker system prune -a -f

            # Build and start containers
            sudo docker compose up --build -d

            # Show running containers
            sudo docker compose ps